/*
 * Copyright (C) 2018 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.cloud.demo.iot.nirvana.datastore.entity;

/**
 * Message class describes a message generated by a simulated device that will be published into
 * PubSub and then streamed into DataStore and BigQuery via DataFlow.
 */
public class Message {

  String id;
  double temperature;
  long timestamp;

  public Message() {
    ;
  }

  /**
   * Create the new message
   *
   * @param id the id of the message MD5(lat+"-"+lng)
   * @param temperature the temperature to be published
   * @param timestamp the UNIX epoch time
   */
  public Message(String id, double temperature, long timestamp) {
    this.id = id;
    this.temperature = temperature;
    this.timestamp = timestamp;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public double getTemperature() {
    return temperature;
  }

  public void setTemperature(double temperature) {
    this.temperature = temperature;
  }

  public long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(long timestamp) {
    this.timestamp = timestamp;
  }
}
